personal_portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

from portfolio import views

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/', include('portfolio.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from portfolio import views

app_name = 'portfolio'

urlpatterns = [
    path('hero/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('work/', views.work, name='work'),
    path('project/<str:pk>/', views.view_project, name='project'),
    path("project_listing/", views.ProjectListing.as_view(), name='project_listing'),
]

portfolio/models.py
from django.db import models
import os
import xml.etree.cElementTree as et
from uuid import uuid4
from django.utils.deconstruct import deconstructible

@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)

path_and_rename = PathAndRename("projects_images/")
logo_path_and_rename = PathAndRename("projects_logos/")

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Project(models.Model):
    name = models.CharField(max_length=128, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    logo = models.FileField(upload_to=logo_path_and_rename, null=True, blank=True, max_length=255)
    picture = models.ImageField(upload_to=path_and_rename, null=True, blank=True, max_length=255)
    title = models.CharField(max_length=128)
    subtitle = models.CharField(max_length=128)
    description = models.CharField(max_length=255)
    project_description = models.CharField(max_length=1024, null=True, blank=True)
    project_roles = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name
    
class ProjectImages(models.Model):
    project_name = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=path_and_rename, null=True, blank=True, max_length=255)
    
    class Meta:
        verbose_name_plural = 'Project Images'

    def __str__(self):
        return str(self.project_name)

portfolio/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.views import View
from rest_framework.generics import ListAPIView
from .serializers import ProjectSerializers
from portfolio.models import Category, Project, ProjectImages

def index(request):
    context_dict = {}
    context_dict['title'] = 'Home'

    return render(request, 'portfolio/index.html', context_dict)

def about(request):
    context_dict = {}
    context_dict['title'] = 'About'

    return render(request, 'portfolio/about.html', context_dict)

def work(request):
    category_list = Category.objects.all().order_by('id')

    context_dict = {}
    context_dict['title'] = 'Work'
    context_dict['categories'] = category_list

    return render(request, 'portfolio/work.html', context_dict)

def view_project(request, pk):
    try:
        project = Project.objects.get(id=pk)
        roles = project.project_roles.split(",")
        images = ProjectImages.objects.all().filter(project_name_id=pk)
        print(images)
    except Project.DoesNotExist:
        return redirect(reverse('work'))

    context_dict = {'project': project, 'roles': roles, 'images': images}
    return render(request, 'portfolio/view_project.html', context_dict)


class ProjectListing(ListAPIView):
    serializer_class = ProjectSerializers

    def get_queryset(self):
        queryList = Project.objects.all()
        category = self.request.query_params.get('category', None)
        if category:
            queryList = queryList.filter(category__name = category)          
        return queryList
    
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

templates/portfolio/about.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title_block %}
    Łukasz Sokołowski Portfolio - {{ title }}
{% endblock %}

{% block main_block %}
<main class="about">
    <div class="about-wrapper">
        <div class="about__description-wrapper">
            <div class="about__description">
                <div class="about__title">
                    <p>Who am I?</p>
                </div>
                <div class="about__content">
                    <p>
                        I am Łukasz Sokołowski, MSc in automation, robotics and industrial informatics, currently working in Warsaw as a Software Engineer in Deloitte.
                    </p>
                    <br>
                    <p>
                        In my career here I have been involved in:
                        <ul>
                            <li>• &nbsp;a project for a leading Slovak bank as the Lead Migration Developer,</li>
                            <li>• &nbsp;a project for one of the leading Hungarian banks,</li>
                            <li>• &nbsp;analysis of customer data,</li>
                            <li>• &nbsp;analysis of data migration - mapping, bug fixing and reporting,</li>
                            <li>• &nbsp;analysis of performance issues - daily and monthly generated reports,</li>
                            <li>• &nbsp;preparation of processes and reconciliation reports,</li>
                            <li>• &nbsp;preparation of database packages and database models,</li>
                            <li>• &nbsp;supporting analysts on technical issues,</li>
                            <li>• &nbsp;supporting bank during migration runs - Test Runs, Dry-Runs and Go-Lives,</li>
                            <li>• &nbsp;supporting the development of new functionalities and testing of the software for data migration and reconciliation,</li>
                            <li>• &nbsp;optimisation of migration processes and SQL queries in terms of performance and readability,</li>
                            <li>• &nbsp;development of Jenkins pipelines (CI/CD),</li>
                            <li>• &nbsp;development of Spring Boot web app (CI/CD practices),</li>
                            <li>• &nbsp;development of Python test data generator,</li>
                            <li>• &nbsp;introducing and supervising the work of developers in own small technical sub-team.</li>
                        </ul>
                        <br>
                        Besides my work, I am working on my frontend/web development skills, as I am self-taught in almost every tech stack, that I have in my portfolio. 
                        Drawing, computer graphics and everything related to it are the things that I always wanted to focus mainly on ever since I can remember. 
                        I am the type of person who takes many opportunities to learn something new, hence I enjoy challenges. 
                        I am a fast learner and like to gain a lot of new experience.
                    </p>
                </div>
                <div class="about__resume">
                    <a class="resume__button" href="{% static 'files/Lukasz-Sokolowski-CV.pdf' %}" download="Lukasz-Sokolowski-CV">
                        <span class="button__line"></span>
                        <span class="button__download">Download my CV!</span>
                        <svg width="164" height="164" viewBox="0 0 164 164" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M122.163 135.722H41.7294C39.2176 135.722 37.1649 137.747 37.1649 140.286C37.1649 142.798 39.1908 144.851 41.7294 144.851H122.19C124.702 144.851 126.754 142.825 126.754 140.286C126.727 137.747 124.702 135.722 122.163 135.722Z" fill="white"/>
                            <path d="M122.163 115.734H41.7294C39.2176 115.734 37.1649 117.76 37.1649 120.299C37.1649 122.811 39.1908 124.863 41.7294 124.863H122.19C124.702 124.863 126.754 122.837 126.754 120.299C126.727 117.76 124.702 115.734 122.163 115.734Z" fill="white"/>
                            <path d="M81.9459 19.1494C71.142 19.1494 62.3102 27.9545 62.3102 38.7851C62.3102 49.589 71.142 58.3937 81.9459 58.3937C92.7498 58.3937 101.582 49.5886 101.582 38.758C101.582 27.9274 92.7498 19.1494 81.9459 19.1494ZM81.9459 49.2381C76.1928 49.2381 71.4662 44.5115 71.4662 38.7584C71.4662 33.0053 76.1657 28.2787 81.9459 28.2787C87.7262 28.2787 92.4256 33.0053 92.4256 38.7584C92.4256 44.5111 87.699 49.2381 81.9459 49.2381Z" fill="white"/>
                            <path d="M108.01 68.2527C91.3451 61.7706 72.6006 61.7706 55.9362 68.2527C50.4802 70.3864 46.834 75.8153 46.834 81.7844V100.313C46.8069 102.824 48.8599 104.877 51.3718 104.877H112.548C115.059 104.877 117.112 102.852 117.112 100.313V81.7844C117.112 75.8153 113.466 70.3864 108.01 68.2527ZM108.01 95.7748H55.9362V81.8112C55.9362 79.5964 57.2598 77.5437 59.2314 76.7875C73.7892 71.1426 90.1569 71.1426 104.715 76.7875C106.687 77.5709 108.01 79.5697 108.01 81.8112V95.7748H108.01Z" fill="white"/>
                            <path d="M130.806 0H54.9369C51.4257 0 48.1305 1.35033 45.6458 3.8354L23.8221 25.6587C21.3374 28.1438 19.9867 31.4386 19.9867 34.9497V150.819C19.9867 158.085 25.9019 164 33.167 164H130.833C138.098 164 144.013 158.084 144.013 150.819V13.1803C143.932 5.9152 138.017 0 130.806 0ZM46.8069 15.5572V26.8469H35.5171L46.8069 15.5572ZM134.83 48.8056H117.868C115.356 48.8056 113.304 50.8315 113.304 53.3701C113.304 55.8819 115.329 57.9346 117.868 57.9346H134.83V66.0374H128.618C126.106 66.0374 124.053 68.0628 124.053 70.6018C124.053 73.1136 126.079 75.1663 128.618 75.1663H134.83V150.846C134.83 153.088 133.021 154.897 130.806 154.897H33.0864C30.8716 154.897 29.0621 153.088 29.0621 150.873V35.9491H51.3718C53.8836 35.9491 55.9362 33.9236 55.9362 31.3847V9.07502H130.806C133.021 9.07502 134.83 10.8845 134.83 13.0993V48.8056Z" fill="white"/>
                        </svg>
                    </a>                                 
                </div>
            </div>
        </div>
        <div class="about__picture">
            <img src="{% static 'images/hero-pic-side.png' %}" alt="hero-pic-side.png">
        </div>
    </div>
    <div class="about__skills">
        <p>Tech Stack</p>
        <div class="skills">
            <div class="skills__element">
                <img src="{% static 'svg/react.svg' %}"  alt="react.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/html.svg' %}"  alt="html.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/css.svg' %}"  alt="css.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/javascript.svg' %}"  alt="javascript.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/tailwind.svg' %}" alt="tailwind.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/python.svg' %}"  alt="python.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/django.svg' %}"  alt="django.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/oracle-sql.svg' %}"  alt="oraclesql.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/figma.svg' %}"  alt="figma.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/unreal-engine.svg' %}"  alt="unrealengine.svg">
            </div>
            <div class="skills__element">
                <img src="{% static 'svg/photoshop.svg' %}"  alt="photoshop.svg">
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>
        {% block title_block %}
            Łukasz Sokołowski Portfolio - Hero
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS -->
    <link rel="stylesheet" href="/../static/css/styles.css?v=4.0"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Press Start 2P">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Libre Bodoni">
    <script src="https://kit.fontawesome.com/f6de6d0aad.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="{% static 'js/mobile-settings.js' %}"></script>
    <script src="{% static 'js/mobile-detect.js' %}"></script>
    <script src="{% static 'js/jquery.fittext.js' %}"></script>
    {% block head_block %}
    {% endblock %}
</head>
<body>
    <nav id="nav-bar">
        <div class="nav__logo">
            <p><a href="{% url 'portfolio:index' %}"></a></p>
        </div>
        <div class="nav__menu" id="nav-menu">
            <div class="menu-button" id="menu-button" aria-controls="primary-navigation" aria-expanded="false">
                <svg stroke="var(--menu-button-color)" fill="none" class="hamburger" viewBox="-10 -10 120 120" width="60">
                  <path class="line" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" d="m 20 40 h 60 a 1 1 0 0 1 0 20 h -60 a 1 1 0 0 1 0 -40 h 30 v 70">
                  </path>
                </svg>
            </div>
            <ul class="nav__list" id="nav-list" aria-expanded="false">
                <li {% if request.resolver_match.url_name == 'index' %}class="nav__item active"{% else %}class="nav__item"{% endif %}>
                    <a class="nav__link" href="{% url 'portfolio:index' %}">HOME</a>
                </li>
                <li {% if request.resolver_match.url_name == 'about' %}class="nav__item active"{% else %}class="nav__item"{% endif %}>
                    <a class="nav__link" href="{% url 'portfolio:about' %}">ABOUT</a>
                </li>
                <li {% if request.resolver_match.url_name == 'work' %}class="nav__item active"{% else %}class="nav__item"{% endif %}>
                    <a class="nav__link" href="{% url 'portfolio:work' %}">WORK</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block main_block %}
    {% endblock %}
    <footer>
        <div class="footer__container">
            <div class="footer__socials">
                <a aria-label="linkedin" target="_blank" rel="noreferrer" href="https://www.linkedin.com/in/łukasz-sokołowski-32a379244/">
                    <i class="fa-brands fa-linkedin fa-xl"></i>
                </a>
                <!-- <a class="disabled-link" aria-label="email" target="_blank" rel="noreferrer" href="#">
                    <i class="fa-regular fa-envelope fa-xl"></i>
                </a> -->
            </div>
            <div class="footer__copyrights">
                <p>&copy; 2023 Created by Łukasz Sokołowski. All Rights Reserved.</p>
            </div>
        </div>
    </footer>
</body>
<script src="{% static 'js/hero.js' %}?v=3.1"></script>
<script src="{% static 'js/nav.js' %}"></script>
{% block script_block %}
{% endblock %}
</html>

templates/portfolio/index.html
{% extends 'portfolio/base.html' %} {% load static %} {% block title_block %}
Łukasz Sokołowski Portfolio - {{ title }} {% endblock %} {% block main_block %}
<main class="hero">
  <div class="hero-wrapper">
    <div class="hero__message--top">
      <p class="message__title--top">HELLO THERE!</p>
      <p class="message__subtitle--top">
        I'M <span class="golden">LUKASZ</span>
      </p>
    </div>
    <div class="hero__profession">
      <p>FULL-STACK DEVELOPER</p>
    </div>
    <div class="hero__picture">
      <img src="{% static 'images/hero-pic.png' %}" alt="hero-pic.png" />
    </div>
    <div class="hero__message--bottom">
      <p class="message__title--bottom">and this is my...</p>
      <p class="message__subtitle--bottom golden">PORTFOLIO</p>
    </div>
  </div>
</main>
{% endblock %}

templates/portfolio/view_project.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title_block %}
    Łukasz Sokołowski Portfolio - {{ project.name }}
{% endblock %}

{% block main_block %}
<main class="project">
    <div class="project-wrapper">
        <div class="project__button">
            <a href="{% url 'portfolio:work' %}">
                <svg width="35" height="58" viewBox="0 0 35 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M34.6569 6.37267L29 0.71582L0.715729 29.0001L29 57.2844L34.6569 51.6275L12.0294 29.0001L34.6569 6.37267Z" fill="#FFF"/>
                </svg>
            </a>
        </div>
        <div class="project__logo" style="background-image: url(../../..{{ project.logo.url }});"></div>
        <div class="project__content">               
            <p class="project__title">{{ project.title }}</p>
            <p class="project__subtitle">{{ project.subtitle }}</p>
            <div class="project__story">
                <div class="project__description">{{ project.project_description }}</div>
                <div class="project__role">
                    <p>MY ROLE</p>
                    <ul>
                        {% for role in roles %}
                        <li>• &nbsp;{{ role }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div data-open-modal class="project__gallery">
            <span class="gallery__button-line"></span>
            <span class="gallery__button-view">See the gallery</span>
            <svg width="223" height="190" viewBox="0 0 223 190" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect x="5.9502" y="54.7373" width="170" height="130" rx="11" stroke="white" stroke-width="10"/>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M20.9502 75.7402C20.9502 72.4265 23.6365 69.7402 26.9502 69.7402H154.95C158.264 69.7402 160.95 72.4265 160.95 75.7402V133.99L135.626 108.175C131.957 104.435 126.024 104.16 122.025 107.546L96.0759 129.519C92.8989 132.209 88.3877 132.65 84.7503 130.625L62.6122 118.303C59.7462 116.708 56.2802 116.62 53.3367 118.067L20.9502 133.99V75.7402ZM50.1488 89.173C50.1488 93.2967 46.8058 96.6396 42.6821 96.6396C38.5584 96.6396 35.2154 93.2967 35.2154 89.173C35.2154 85.0493 38.5584 81.7063 42.6821 81.7063C46.8058 81.7063 50.1488 85.0493 50.1488 89.173Z" fill="white"/>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M212.254 57.0332L75.0711 1.49106C66.8804 -1.82516 57.5522 2.12637 54.236 10.3171L35.3916 56.8605H46.1801L63.5051 14.0699C64.7487 10.9984 68.2468 9.51657 71.3183 10.7602L208.501 66.3023C211.572 67.5459 213.054 71.044 211.811 74.1155L175.672 163.373V182.614H149.374L159.714 186.801C167.905 190.117 177.233 186.165 180.549 177.975L221.08 77.8683C224.396 69.6776 220.444 60.3494 212.254 57.0332Z" fill="white"/>
            </svg>                                       
        </div>
        <dialog data-modal class="gallery-modal">
            <div data-close-modal class="close-btn">
                <svg width="59" height="58" viewBox="0 0 59 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M6.11035 0.71582L0.453613 6.37256L23.0811 29L0.453613 51.6274L6.11035 57.2842L29.5322 33.8623L52.9541 57.2842L58.6108 51.6274L35.9834 29L58.6108 6.37256L52.9541 0.71582L29.5322 24.1377L6.11035 0.71582Z" fill="#D9D9D9"/>
                </svg>
            </div>
            <div class="gallery__arrow gallery__arrow--left">
                <svg width="35" height="58" viewBox="0 0 35 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M34.6569 6.37267L29 0.71582L0.715729 29.0001L29 57.2844L34.6569 51.6275L12.0294 29.0001L34.6569 6.37267Z" fill="#FFF"/>
                </svg>
            </div>
            <div class="gallery__arrow gallery__arrow--right">
                <svg width="35" height="58" viewBox="0 0 35 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M0.855841 6.37267L6.5127 0.71582L34.797 29.0001L6.5127 57.2844L0.855841 51.6275L23.4833 29.0001L0.855841 6.37267Z" fill="#FFF"/>
                </svg> 
            </div>
            <div class="gallery__images">
                {% if images %}
                    {% for image in images %}
                        {% if forloop.first %}
                        <img class="gallery__image" src="../../..{{ image.image.url }}" alt="">
                        {% else %}
                        <img class="gallery__image gallery__image--hidden" src="../../..{{ image.image.url }}" alt="">
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </dialog>
    </div>
</main>
{% endblock %}
{% block script_block %}
<script src="{% static 'js/gallery.js' %}"></script>
{% endblock %}

templates/portfolio/work.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title_block %}
    Łukasz Sokołowski Portfolio - {{ title }}
{% endblock %}

{% block head_block %}
    <script src="{% static 'js/jquery.dragnscroll.min.js' %}"></script>
{% endblock %}

{% block main_block %}
<main class="work-main">
    <div class="slider-wrapper">
        <div class="slider__menu">
            <div class="menu__title">
                <p>My Projects</p>
            </div>
            <div class="menu__categories" id="categories">
                <div class="menu__arrow menu__arrow--left">
                    <svg width="35" height="58" viewBox="0 0 35 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M34.6569 6.37267L29 0.71582L0.715729 29.0001L29 57.2844L34.6569 51.6275L12.0294 29.0001L34.6569 6.37267Z" fill="#FFF"/>
                    </svg>
                </div>
                <div class="menu__slider">
                {% if categories %}
                    <div class="menu__category active" id="all_categories" data-attr="{{ category.name }}">
                        <a class="category__link" href="#">ALL</a>
                    </div>
                    {% for category in categories %}
                        <div class="menu__category" data-attr="{{ category.name }}">
                            <a class="category__link" href="#">{{ category.name }}</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}
                </div>
                <div class="menu__arrow menu__arrow--right">
                    <svg width="35" height="58" viewBox="0 0 35 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M0.855841 6.37267L6.5127 0.71582L34.797 29.0001L6.5127 57.2844L0.855841 51.6275L23.4833 29.0001L0.855841 6.37267Z" fill="#FFF"/>
                    </svg>                        
                </div>
            </div>
            <div class="menu__nav">
                <div class="nav__track nav__track--left"></div>
                <div class="nav__thumb" id="menu_thumb">
                    <div class="nav__thumb--inner"></div>
                    <div class="nav__thumb--outer"></div>
                </div>
                <div class="nav__track nav__track--right"></div>
                <div class="nav__track nav__track--full"></div>
            </div>
        </div>
        <div class="slider">
            <div class="slider__slides" id="slides" url="{% url 'portfolio:project_listing' %}">
            </div>
        </div>
        <div class="slider__scrollbar">
            <div class="scrollbar__elements">
                <div class="scrollbar__track"></div>
                <div class="scrollbar__thumb">
                    <div class="scrollbar__thumb--inside"></div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}
{% block script_block %}
<script src="{% static 'js/projects.js' %}?v=3.1" type="text/javascript"></script>
<script src="{% static 'js/slider-scrollbar.js' %}?v=3.1" type="text/javascript"></script>
{% endblock %}